AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sb-nippo-kaku-lambda-go
      Runtime: go1.x
      FunctionName: sb-nippo-kaku-go
      Timeout: 30
      Role: arn:aws:iam::486414336274:role/invoke-lastorder
      Environment:
        Variables:
          PROJECT: https://scrapbox.io/rebuild-kitashirakawa
          lastOrder: arn:aws:lambda:ap-northeast-1:486414336274:function:lastOrder
